networks:
  expense: {}
volumes:
  mysql:
services:
  mysql:
    image: santhoshdatti/mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  
  backend:
    image: santhoshdatti/backend:1.0.0
    command: sh -c "sleep 10 && node /opt/backend/index.js"
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql

  frontend:
    image: santhoshdatti/frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend


  